version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby

    steps:
      - checkout

      - run:
          name: Install awesome_bot
          command: gem install awesome_bot

      - run:
          name: Check README.md
          command: awesome_bot README.md --allow-redirect --allow-dupe -w www.terraform.io,signup.hangops.com,kitchen.ci --white-list https://vimeo.com/289905221,kubernetes.io,kitchen.ci
